sudo: required
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
services:
  - docker
before_install:
  - docker pull rabbitmq:3-management
  - "docker run -d -h rabbit1 -p 15672:15672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest -name rabbit1 rabbitmq:3-management"
  - docker ps -a
install:
  - pip install flake8 nose>=1.3.0 coverage coveralls
  - pip install -e .[all]
script:
  - flake8 .
  - python setup.py nosetests
  - python setup.py build_sphinx
after_success:
  coveralls
